version: '3.7'

services:
  postgres-test:
    container_name: postgres-test
    image: postgres
    environment:
      POSTGRES_DB: moja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Krzysiek123qweasd.
    volumes:
      - ./postgres-test:/data/postgres
    expose:
      - "5432"
    ports:
      - "5438:5432"
    command: -p 5432
    restart: always


  demo:
    build: ./demo
    ports:
      - "8888:8888"
    environment:
      - spring.profiles.active=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.instance.hostname=localhost
    links:
      - eureka
    depends_on:
      - eureka


  gateway:
    build: ./gateway
    ports:
      - "8083:8083"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.instance.hostname=localhost
    links:
      - eureka
      - demo
      - micro2
    depends_on:
      - eureka


  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    depends_on:
      - postgres-test





  micro2:
    build: ./micro2
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.instance.hostname=localhost
    links:
      - eureka